from datasets.utils import CHARS, PAD_TOKEN, characters_to_ints

DEVICE = 'cuda'
IMAGE_SIZE = 128, 512
PATCH_WIDTH = 16
PATCH_SIZE = IMAGE_SIZE[0], PATCH_WIDTH
ATTENTION_FEATURE_SIZE = 256
NUM_PATCHES = IMAGE_SIZE[1] // PATCH_WIDTH
NUM_ATTENTION_HEADS = 8
NETWORK_FEATURE_SIZE = 256
NUM_LAYERS = 8
MLP_RATIO = 2
MLP_FEATURE_SIZE = NETWORK_FEATURE_SIZE*MLP_RATIO
NUMBER_OF_CLASSES = len(CHARS)
PADDING_IDX = characters_to_ints(PAD_TOKEN)
