from datasets.utils import CHARS, PAD_TOKEN, characters_to_ints

BATCH_SIZE = 64
MLP_RATIO = 4
NUM_LAYERS = 6
DEVICE = 'cuda'
PATCH_WIDTH = 16
IMAGE_SIZE = 64, 512
NUM_ATTENTION_HEADS = 6
MAX_PATCHES_LENGTH = 128
NETWORK_FEATURE_SIZE = 768
NUMBER_OF_CLASSES = len(CHARS)
PATCH_SIZE = IMAGE_SIZE[0], PATCH_WIDTH
NUM_PATCHES = IMAGE_SIZE[1] // PATCH_WIDTH
PADDING_IDX = characters_to_ints(PAD_TOKEN)
MLP_FEATURE_SIZE = NETWORK_FEATURE_SIZE*MLP_RATIO
ATTENTION_FEATURE_SIZE = NETWORK_FEATURE_SIZE // NUM_ATTENTION_HEADS
